#ifndef B2069796_5717_4F87_816B_9C9E2F02C162
#define B2069796_5717_4F87_816B_9C9E2F02C162

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>

// all-MiniLM-L6-v2 produces 384-dimensional embeddings.
// Baked into Chunk's type, so swapping models means changing this and recompiling.

// inline + constexpr allows a global variable to be evaluated at compile time
// while also allowing it to be defined in a header file without violating the One Definition Rule (ODR)
inline constexpr std::size_t EMBEDDING_DIM = 384;

// Each chunk will represent a line within a file
// Explicit move constructor should only be defined if Chunk manages a resource manually
// such as a raw_pointer, file handle, or other ownership that requires special cleanup
// In this case, the compiler automatically moves each member
//
// embedding is a std::array, not a std::vector, so the floats live *inside* the Chunk
// rather than in a separate heap allocation somewhere else in memory. A similarity scan
// over std::vector<Chunk> then walks memory at a fixed stride instead of chasing one
// pointer per chunk, which lets the CPU's prefetcher predict the access pattern.
// Measured at 50k chunks: ~1.5x faster scan than a std::vector<float> member.
struct Chunk {
    std::uint64_t id; // The ID of the chunk - corresponding to the line number
    std::array<float, EMBEDDING_DIM> embedding; // The embedding generated by all-minilm-v6
    std::string text; // The text inside the chunk
    std::string file_path; // Which file did it come from?
};

#endif /* B2069796_5717_4F87_816B_9C9E2F02C162 */
